---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/dogs":
    get:
      summary: list dogs
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
